language: cpp

sudo: true

os:
  - linux

dist: xenial

compiler:
  - clang
  - gcc

env:
  matrix:
    - CMAKE_BUILD_TYPE=Release
    - CMAKE_BUILD_TYPE=Debug

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang



addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgmp-dev
      - libreadline-dev
      - bison
      - flex

install: true
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
  - make
  - ctest
